spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8071/pessoas
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          use_get_generated_keys: false
          lob:
            non_contextual_creation: false
  jackson:
    property-name-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: true
server:
  port: 8081